/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    'api-log-index': RouteRecordInfo<'api-log-index', '/api-log/Index', Record<never, never>, Record<never, never>>,
    'app-data-form': RouteRecordInfo<'app-data-form', '/app-data/Form', Record<never, never>, Record<never, never>>,
    'app-data-index': RouteRecordInfo<'app-data-index', '/app-data/Index', Record<never, never>, Record<never, never>>,
    'auth-forgot-password': RouteRecordInfo<'auth-forgot-password', '/auth/ForgotPassword', Record<never, never>, Record<never, never>>,
    'auth-login': RouteRecordInfo<'auth-login', '/auth/Login', Record<never, never>, Record<never, never>>,
    'auth-register': RouteRecordInfo<'auth-register', '/auth/Register', Record<never, never>, Record<never, never>>,
    'auth-reset-password': RouteRecordInfo<'auth-reset-password', '/auth/ResetPassword', Record<never, never>, Record<never, never>>,
    'auth-verify-login': RouteRecordInfo<'auth-verify-login', '/auth/VerifyLogin', Record<never, never>, Record<never, never>>,
    'categories-form': RouteRecordInfo<'categories-form', '/categories/Form', Record<never, never>, Record<never, never>>,
    'categories-index': RouteRecordInfo<'categories-index', '/categories/Index', Record<never, never>, Record<never, never>>,
    'dashboard-index': RouteRecordInfo<'dashboard-index', '/dashboard/Index', Record<never, never>, Record<never, never>>,
    'error': RouteRecordInfo<'error', '/Error', Record<never, never>, Record<never, never>>,
    'menu-form': RouteRecordInfo<'menu-form', '/menu/Form', Record<never, never>, Record<never, never>>,
    'menu-index': RouteRecordInfo<'menu-index', '/menu/Index', Record<never, never>, Record<never, never>>,
    'misc-coming-soon': RouteRecordInfo<'misc-coming-soon', '/misc/ComingSoon', Record<never, never>, Record<never, never>>,
    'misc-under-maintenance': RouteRecordInfo<'misc-under-maintenance', '/misc/UnderMaintenance', Record<never, never>, Record<never, never>>,
    'notification-form': RouteRecordInfo<'notification-form', '/notification/Form', Record<never, never>, Record<never, never>>,
    'notification-index': RouteRecordInfo<'notification-index', '/notification/Index', Record<never, never>, Record<never, never>>,
    'permission-add-edit-permission-dialog': RouteRecordInfo<'permission-add-edit-permission-dialog', '/permission/AddEditPermissionDialog', Record<never, never>, Record<never, never>>,
    'permission-index': RouteRecordInfo<'permission-index', '/permission/Index', Record<never, never>, Record<never, never>>,
    'posts-form': RouteRecordInfo<'posts-form', '/posts/Form', Record<never, never>, Record<never, never>>,
    'posts-index': RouteRecordInfo<'posts-index', '/posts/Index', Record<never, never>, Record<never, never>>,
    'posts-show': RouteRecordInfo<'posts-show', '/posts/Show', Record<never, never>, Record<never, never>>,
    'profile-about': RouteRecordInfo<'profile-about', '/profile/About', Record<never, never>, Record<never, never>>,
    'profile-account-settings-account': RouteRecordInfo<'profile-account-settings-account', '/profile/AccountSettingsAccount', Record<never, never>, Record<never, never>>,
    'profile-account-settings-security': RouteRecordInfo<'profile-account-settings-security', '/profile/AccountSettingsSecurity', Record<never, never>, Record<never, never>>,
    'profile-profile': RouteRecordInfo<'profile-profile', '/profile/Profile', Record<never, never>, Record<never, never>>,
    'profile-profile-edit': RouteRecordInfo<'profile-profile-edit', '/profile/ProfileEdit', Record<never, never>, Record<never, never>>,
    'role-add-edit-role-dialog': RouteRecordInfo<'role-add-edit-role-dialog', '/role/AddEditRoleDialog', Record<never, never>, Record<never, never>>,
    'role-index': RouteRecordInfo<'role-index', '/role/Index', Record<never, never>, Record<never, never>>,
    'role-role-cards': RouteRecordInfo<'role-role-cards', '/role/RoleCards', Record<never, never>, Record<never, never>>,
    'role-user-list': RouteRecordInfo<'role-user-list', '/role/UserList', Record<never, never>, Record<never, never>>,
    'tags-form': RouteRecordInfo<'tags-form', '/tags/Form', Record<never, never>, Record<never, never>>,
    'tags-index': RouteRecordInfo<'tags-index', '/tags/Index', Record<never, never>, Record<never, never>>,
    'user-add-new-user-drawer': RouteRecordInfo<'user-add-new-user-drawer', '/user/AddNewUserDrawer', Record<never, never>, Record<never, never>>,
    'user-edit': RouteRecordInfo<'user-edit', '/user/Edit', Record<never, never>, Record<never, never>>,
    'user-form': RouteRecordInfo<'user-form', '/user/Form', Record<never, never>, Record<never, never>>,
    'user-index': RouteRecordInfo<'user-index', '/user/Index', Record<never, never>, Record<never, never>>,
    'user-user-bio-panel': RouteRecordInfo<'user-user-bio-panel', '/user/UserBioPanel', Record<never, never>, Record<never, never>>,
    'user-user-tab-security': RouteRecordInfo<'user-user-tab-security', '/user/UserTabSecurity', Record<never, never>, Record<never, never>>,
    'user-view': RouteRecordInfo<'user-view', '/user/View', Record<never, never>, Record<never, never>>,
  }
}
