apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: localhost:5000/web-app:latest  
          imagePullPolicy: Always
          ports:
            - containerPort: 9000

          resources:             
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          volumeMounts:
            - name: env-config
              mountPath: /var/www/html/.env
              subPath: .env

      volumes:
        - name: env-config
          hostPath:
            path: /www/wwwroot/csl_laravel_starter_kit/.env
            type: File
